version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: codebreaker-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: codebreaker-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: codebreaker-backend
    depends_on:
      - postgres
      - rabbitmq
      - code-executor
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - EXECUTOR_SERVICE_URL=http://code-executor:8081/api/execute
    restart: unless-stopped

  code-executor:
    build: ./code-executor
    container_name: code-executor
    ports:
      - "8081:8081"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - rabbitmq

  frontend:
    build: ./frontend
    container_name: codebreaker-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    restart: unless-stopped

volumes:
  postgres_data:
